INSERT INTO lists (_id,
                   list_name,
                   list_created,
                   list_modified,
                   list_deleted,
                   locked,
                   archived,
                   position,
                   smart,
                   filter,
                   rtm_list_id)
   VALUES (1,
           "NonSmartList",
           ${today},
           ${today},
           NULL,
           0,
           0,
           -1,
           0,
           NULL,
           "1000");
        
INSERT INTO lists (_id,
                   list_name,
                   list_created,
                   list_modified,
                   list_deleted,
                   locked,
                   archived,
                   position,
                   smart,
                   filter,
                   rtm_list_id)
   VALUES (2,
           "SmartList",
           ${yesterday},
           ${yesterday},
           NULL,
           0,
           1,
           0,
           1,
           "(name:test)",
           "1001");
