INSERT INTO lists (_id,
                   list_name,
                   list_created,
                   list_modified,
                   list_deleted,
                   locked,
                   archived,
                   position,
                   smart,
                   filter,
                   rtm_list_id)
   VALUES (1000,
           "List1",
           1356998400000,
           1356998400001,
           NULL,
           0,
           0,
           -1,
           0,
           NULL,
           "10000");     
           
INSERT INTO locations (  _id,
                         location_name,
                         longitude,
                         latitude,
                         address,
                         viewable,
                         zoom,                       
                         rtm_location_id)
   VALUES (2000,
           "Location1",
           1.0,
           2.0,
           NULL,
           1,
           10,
           "20000");
           
INSERT INTO locations (  _id,
                         location_name,
                         longitude,
                         latitude,
                         address,
                         viewable,
                         zoom,                       
                         rtm_location_id)
   VALUES (2001,
           "Location2",
           1.0,
           2.0,
           NULL,
           1,
           10,
           "20001");

INSERT INTO taskseries ( _id,
                         task_created,
                         task_modified,
                         task_name,
                         source,
                         url,
                         recurrence,
                         recurrence_every,
                         location_id,
                         rtm_location_id,
                         list_id,
                         rtm_list_id,
                         tags,
                         rtm_taskseries_id)
   VALUES (10,
           1356998400000,
           1356998400001,
           "Task1",
           "JUNIT",
           "http://abc.de",
           "every 2 days",
           1,
           2000,
           "20000",
           1000,
           "10000",
           "tag1,tag2",
           "1000");
        
INSERT INTO rawtasks ( _id,
                      due,
                      has_due_time,
                      added,
                      completed,
                      deleted,
                      priority,
                      postponed,
                      estimate,
                      estimateMillis,
                      rtm_rawtask_id,
                      taskseries_id)
   VALUES (1,
           1356998400002,
           1,
           1356998400003,
           1356998400004,
           1356998400005,
           'n',
           2,
           "1h",
           36000000,
           "5000",
           10);
